"""add_email_and_address_to_user

Revision ID: 0487d528890c
Revises: 4c42cc24b60f
Create Date: 2026-05-13 11:40:39.326693
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0487d528890c'
down_revision: Union[str, None] = '4c42cc24b60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
