"""make_recruiter_id_nullable

Revision ID: 1acdafcb68bb
Revises: 0487d528890c
Create Date: 2026-05-13 11:45:16.835406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1acdafcb68bb'
down_revision: Union[str, None] = '0487d528890c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('recruiter_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('recruiter_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)

    # ### end Alembic commands ###
