"""add_onboarding_session

Revision ID: 4c42cc24b60f
Revises: fda55c0e2ced
Create Date: 2026-05-13 07:33:37.921568
"""

from collections.abc import Sequence

revision: str = "4c42cc24b60f"
down_revision: str | None = "fda55c0e2ced"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
