"""add source fields to jobs

Revision ID: 6e95df7f968f
Revises: 002
Create Date: 2026-05-09 12:56:19.432388
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6e95df7f968f"
down_revision: str | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("source_url", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column("jobs", sa.Column("source_name", sa.String(length=100), nullable=True))
    op.add_column(
        "jobs", sa.Column("is_external", sa.Boolean(), nullable=False, server_default="0")
    )
    op.add_column("jobs", sa.Column("last_seen_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE jobs SET is_external = 0 WHERE is_external IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "last_seen_at")
    op.drop_column("jobs", "is_external")
    op.drop_column("jobs", "source_name")
    op.drop_column("jobs", "external_id")
    op.drop_column("jobs", "source_url")
    # ### end Alembic commands ###
