"""add_structured_cv_tables_final

Revision ID: fda55c0e2ced
Revises: 004_add_credits
Create Date: 2026-05-12 23:43:49.163765
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fda55c0e2ced"
down_revision: str | None = "004_add_credits"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cvs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cv_type", sa.String(length=20), server_default="original", nullable=False)
        )
        batch_op.add_column(sa.Column("job_id", sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column("file_path", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("structured_content", sa.JSON(), nullable=True))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.create_foreign_key(batch_op.f("fk_cvs_job_id_jobs"), "jobs", ["job_id"], ["id"])

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_subscriptions_user_id"), ["user_id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("linkedin_url", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("github_url", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("website_url", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("summary_override", sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_users_telegram_id"), ["telegram_id"])
        batch_op.create_unique_constraint(batch_op.f("uq_users_whatsapp_id"), ["whatsapp_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_whatsapp_id"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_users_telegram_id"), type_="unique")
        batch_op.drop_column("summary_override")
        batch_op.drop_column("website_url")
        batch_op.drop_column("github_url")
        batch_op.drop_column("linkedin_url")

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_subscriptions_user_id"), type_="unique")

    with op.batch_alter_table("cvs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_cvs_job_id_jobs"), type_="foreignkey")
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.drop_column("structured_content")
        batch_op.drop_column("file_path")
        batch_op.drop_column("job_id")
        batch_op.drop_column("cv_type")

    # ### end Alembic commands ###
